import dotenv from "dotenv";
dotenv.config();

const constants = Object.freeze({
  CONST_APP_NAME: process.env.APP_NAME,
  CONST_APP_URL: process.env.APP_URL,
  CONST_APP_VERSION: process.env.APP_VERSION,
  CONST_JWT_TOKEN_KEY: process.env.JWT_TOKEN_KEY,

  // API Response code
  CONST_RESP_CODE_OK: 200,
  CONST_RESP_CODE_CREATED: 200,
  CONST_RESP_CODE_CONTENT_NOT_FOUND: 200,
  CONST_RESP_CODE_DATA_NOT_MODIFIED: 200,
  CONST_RESP_CODE_BAD_REQUEST: 200,
  CONST_RESP_CODE_UNAUTHORIZED: 200,
  CONST_RESP_CODE_NOT_FOUND: 200,
  CONST_RESP_CODE_NOT_ACCEPT: 200,
  CONST_RESP_CODE_INTERNAL_SERVER_ERROR: 500,

  CONST_USER_VERIFIED_TRUE: true,
  CONST_USER_VERIFIED_FALSE: false,

  CONST_GEN_SALT: 10,
  CONST_DB_URL: process.env.MONGODB_URL,

  CONST_ROLE_ADMIN: 1,
  CONST_ROLE_USER: 2,

  CONST_APP_VEDIO: "vedio/",

  CONST_PAGE: 1,
  CONST_LIMIT: 10,

  CONST_RESP_LANG_COLLECTION: ["en"],

  CONST_VALIDATE_SESSION_EXPIRE: "24h",

  CONST_STATUS_ACTIVE: "Active",
  CONST_STATUS_INACTIVE: "In-Active",
  CONST_STATUS_DELETED: "Deleted",

  CONST_SMTP_HOST: process.env.MAIL_HOST,
  CONST_SMTP_PORT: process.env.MAIL_PORT,
  CONST_SMTP_USER: process.env.MAIL_USERNAME,
  CONST_SMTP_PASSWORD: process.env.MAIL_PASSWORD,
  CONST_SMTP_FROM_ADDRESS: process.env.MAIL_FROM_ADDRESS,

  AWS_S3_BUCKET_NAME: process.env.ENV_AWS_S3_BUCKET_NAME,
  AWS_S3_BUCKET_ACCESS_ID: process.env.ENV_AWS_S3_BUCKET_ACCESS_ID,
  AWS_S3_BUCKET_SECRET_ID: process.env.ENV_AWS_S3_BUCKET_SECRET_ID,
  AWS_S3_BUCKET_URL: process.env.ENV_AWS_S3_BUCKET_URL,
  AWS_S3_BUCKET_REGION: process.env.ENV_AWS_S3_BUCKET_REGION,

});

export default constants;
